Adding config service extended implementation
wso2-extensions/apim-migration-resources pull request #181
Opened 2022-05-20 06:26 UTC by CrowleyRajapakse

## Implementation
Engaging extended config service impl with registry based implementation.

2022-05-23 10:36 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/APIUtil.java
> +        APIUtil.disabledExtendedAPIMConfigService = isDisabledExtendedAPIMConfigService;
@CrowleyRajapakse do we need to explictly refer disabledExtendedAPIMConfigService as APIUtl.disabledExtendedAPIMConfigService if in the same class?

2022-05-23 10:55 UTC, CrowleyRajapakse commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/APIUtil.java
> +        APIUtil.disabledExtendedAPIMConfigService = isDisabledExtendedAPIMConfigService;
changed and fixed.

2022-05-23 11:11 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/ExtendedAPIMConfigServiceImpl.java
> +
@CrowleyRajapakse shall we add more info logs on both if else paths for debugging purposes.

2022-05-23 11:12 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/client/V410Migration.java
> +        APIUtil.setDisabledExtendedAPIMConfigService(true);
lets add info logs here as well as we are disabling the service.

2022-05-23 11:47 UTC, CrowleyRajapakse commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/client/V410Migration.java
> +        APIUtil.setDisabledExtendedAPIMConfigService(true);
fixed

2022-05-23 14:08 UTC, tharindu1st requested changes

2022-05-23 14:08 UTC, tharindu1st commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/ExtendedAPIMConfigServiceImpl.java
> +                    APIUtil.loadTenantRegistry(tenantId);
please duplicate this method in migration client

2022-05-23 14:08 UTC, tharindu1st commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/ExtendedAPIMConfigServiceImpl.java
> +                RegistryService registryService = ServiceReferenceHolder.getInstance().getRegistryService();
Don't use ServiceReferenceHolder from apimgt.impl

2022-05-23 14:35 UTC, CrowleyRajapakse commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/ExtendedAPIMConfigServiceImpl.java
> +                    APIUtil.loadTenantRegistry(tenantId);
Resolved, changed the impl APIUtil import to migration util class which already had this duplicated method.

2022-05-23 14:36 UTC, CrowleyRajapakse commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/ExtendedAPIMConfigServiceImpl.java
> +                RegistryService registryService = ServiceReferenceHolder.getInstance().getRegistryService();
changed, resolved.

2022-05-24 05:54 UTC, dushaniw approved these changes

2022-05-24 05:55 UTC, merged