LifeCycle Migrations added
wso2-extensions/apim-migration-resources pull request #265
Opened 2022-08-25 07:15 UTC by shnrndk

## Purpose
> Migrate LifeCycle config from registry to Advance Configuration

## Related PRs
> This fixes wso2/api-manager#364
> Migration Fix for the wso2/api-manager#314

## Migrations
1. Read the LifeCycle.xml file in each tenant and convert that to a respective LifeCycle Object.
2. Add the converted lifecycle object to tenant-conf.json(or Advanced Configuration of the tenant)
3. Detach the APILifeCycle from the Registry	
4. Pre-validation to validate whether lcState is same as the overview_status of the API

2022-08-25 07:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2-extensions/apim-migration-resources?pullRequest=265) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2-extensions/apim-migration-resources?pullRequest=265) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2-extensions/apim-migration-resources?pullRequest=265) it.</sub>

2022-08-25 07:25 UTC, chamilaadhi requested changes

2022-08-25 07:25 UTC, chamilaadhi commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +//            ObjectMapper mapper = new ObjectMapper();
remove commented out sections

2022-08-25 07:25 UTC, chamilaadhi commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                }else{
format

2022-08-25 07:25 UTC, chamilaadhi commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +
plz format your code sections

2022-08-25 07:25 UTC, chamilaadhi commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                        }
Remove lifecycle after doing this operation. if you remove the lifecycle from the API before this step, lcState will always be null.

2022-08-25 07:32 UTC, chamilaadhi commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +    private JSONObject returnLifeCycleAsJson(String lcXML) throws ParserConfigurationException, IOException, SAXException {
please use a meaningfull method name and parameter name. ex: convertLifecycleToJSON(l

2022-08-25 07:34 UTC, chamilaadhi requested changes

2022-08-25 07:34 UTC, chamilaadhi commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                    log.info("ArtifactManager Is Null");
We shouldn't ignore if there is an error. plz add a proper error handling

2022-08-25 08:25 UTC, chamilaadhi commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                    if (checkListItems.size() > 0) stateObj.put("CheckItems", checkListItems);
use below instead of doing one line
``` 
if () {
}
```

2022-08-26 09:31 UTC, chamilaadhi commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                        log.info("lcState: " + lcState);
you have added a log to print the states. but this is not enough to identify any issue. if logs are needed, add API uuid or API name-provider-version combination

2022-08-26 10:31 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                        log.info("lcState: " + lcState);
Done

2022-08-29 09:55 UTC, chamilaadhi submitted a review, later dismissed

2022-09-21 09:52 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +
remove additional line

2022-09-21 09:52 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +
lets remove additional lines

2022-09-21 09:54 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                log.error("WSO2 API-M Migration Task : Error occurred while getting the Lifecycle XML ");
lets log the exception as well.

2022-09-21 09:55 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                    throw new APIMigrationException("Artifact Manager is Null");
better to make the error more descriptive. Eg: Error while migrating lifecycle xml etc.

2022-09-21 09:55 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +
lets remove these additional new lines

2022-09-21 09:55 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                        log.info("API_ID: "+artifact.getId() + " : API_OVERVIEW_STATUS: " + apiOverviewStatus+" lcState: " + lcState);
formatting issue

2022-09-21 09:55 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                        if (artifact.getPath().contains("/apimgt/applicationdata/provider")) {
can we add this strings as constants

2022-09-21 09:56 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                        String aspect = "APILifeCycle";
shall we use constants for this

2022-09-21 09:57 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +        JSONObject LCConfigObj = new JSONObject();
better add meaningful info logs for each step, it is beneficial to trace and debug whenever issues come during migration

2022-09-21 09:58 UTC, dushaniw commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +
better add start and completing logs for lifecycle configuration migration

2022-09-21 09:59 UTC, dushaniw requested changes
comment on few places. Try to add more info logs in to the code for debugging purposes.

Shall we add some unit test cases as well for this?

2022-09-21 10:15 UTC, shnrndk commented
> comment on few places. Try to add more info logs in to the code for debugging purposes.
> 
> Shall we add some unit test cases as well for this?

Sure I will add unit tests for this and will add more logs.

2022-10-24 11:45 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +        JSONObject LCConfigObj = new JSONObject();
Done

2022-10-24 11:49 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +
Done

2022-10-24 11:49 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                        String aspect = "APILifeCycle";
Done

2022-10-24 11:50 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                        log.info("API_ID: "+artifact.getId() + " : API_OVERVIEW_STATUS: " + apiOverviewStatus+" lcState: " + lcState);
Done

2022-10-24 11:51 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +
Done

2022-10-24 11:51 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                    throw new APIMigrationException("Artifact Manager is Null");
Done

2022-10-24 11:51 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +                log.error("WSO2 API-M Migration Task : Error occurred while getting the Lifecycle XML ");
Done

2022-10-24 11:51 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +
Done

2022-10-24 11:51 UTC, shnrndk commented on components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java
> +
Done

2022-11-18 09:14 UTC, dushaniw approved these changes

2022-11-18 10:51 UTC, merged