Adding API revision feature migration steps
wso2-extensions/apim-migration-resources pull request #74
Opened 2021-02-09 08:29 UTC by CrowleyRajapakse

## Issues

https://github.com/wso2/product-apim/issues/9406

2021-02-09 15:00 UTC, wasuradananjith commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
> +            try (PreparedStatement preparedStatement = connection.prepareStatement(GET_ALL_APIS)){
```suggestion
            try (PreparedStatement preparedStatement = connection.prepareStatement(GET_ALL_APIS)) {
```

2021-02-09 15:01 UTC, wasuradananjith commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
> +            try (PreparedStatement preparedStatement = connection.prepareStatement(GET_ALL_APIS)){
Shall we add a space shown above? Also, there are several places like this. Shall we fix those as well?

2021-02-09 15:03 UTC, wasuradananjith commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
> +                        String thumbPath = artifactPath + RegistryConstants.PATH_SEPARATOR + APIConstants.API_ICON_IMAGE;
```suggestion
                        String thumbPath =
                                artifactPath + RegistryConstants.PATH_SEPARATOR + APIConstants.API_ICON_IMAGE;
```

2021-02-09 15:04 UTC, wasuradananjith commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
> +                        String thumbPath = artifactPath + RegistryConstants.PATH_SEPARATOR + APIConstants.API_ICON_IMAGE;
Shall we split this to two lines? Character length has exceeded

2021-02-09 15:06 UTC, wasuradananjith commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
> +                                + wsdlResourcePath;
```suggestion
                        String absoluteWSDLResourcePath = RegistryUtils
                                .getAbsolutePath(RegistryContext.getBaseInstance(),
                                        RegistryConstants.GOVERNANCE_REGISTRY_BASE_PATH) + wsdlResourcePath;
```

2021-02-09 15:06 UTC, wasuradananjith commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
> +                                + wsdlResourcePath;
Shall we split this to two lines? Maximum character length has exceeded

2021-02-09 15:22 UTC, CrowleyRajapakse commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
> +            try (PreparedStatement preparedStatement = connection.prepareStatement(GET_ALL_APIS)){
resolved

2021-02-09 15:22 UTC, CrowleyRajapakse commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
> +                        String thumbPath = artifactPath + RegistryConstants.PATH_SEPARATOR + APIConstants.API_ICON_IMAGE;
resolved

2021-02-09 15:22 UTC, CrowleyRajapakse commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
> +                                + wsdlResourcePath;
resolved

2021-02-10 06:44 UTC, tharindu1st requested changes

2021-02-10 06:44 UTC, tharindu1st commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
> +                        getGovernanceUserRegistry("admin", MultitenantConstants.SUPER_TENANT_ID);
use tenant admin instad of hardcoded "admin"

2021-02-10 15:18 UTC, CrowleyRajapakse commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
> +                        getGovernanceUserRegistry("admin", MultitenantConstants.SUPER_TENANT_ID);
resolved

2021-02-12 07:49 UTC, chamilaadhi approved these changes

2021-02-12 09:27 UTC, tharindu1st approved these changes

2021-02-13 05:53 UTC, merged