Label to VHost and Dynamic environments migration
wso2-extensions/apim-migration-resources pull request #85
Opened 2021-03-03 17:32 UTC by renuka-fernando

## Purpose
$subject

## Approach
- Read labels and label's access URLs
- Convert label to a dynamic environment
- Convert access URL to a VHost
- Delete Labels and Label URLs. (these tables should be dropped, will carry on this by fixing server usage of these tables)
- Deploy API revisions to a dynamic environment with the first VHost of the environment if the API is assigned to a label

## Related Issues
https://github.com/wso2/product-apim/issues/9807

2021-03-03 17:39 UTC, CrowleyRajapakse approved these changes

2021-03-04 09:31 UTC, isharac requested changes

2021-03-04 09:31 UTC, isharac commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
> +                throw new APIMigrationException("Failed to add data to AM_API_RESOURCE_SCOPE_MAPPING table : ", ex);
error message is misleading

2021-03-04 09:31 UTC, isharac commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
> +            throw new APIMigrationException("Failed to add data to AM_API_RESOURCE_SCOPE_MAPPING table : ", ex);
here as well

2021-03-04 09:31 UTC, isharac commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
> +            throw new APIMigrationException("Failed to add data to AM_API_RESOURCE_SCOPE_MAPPING table : ", e);
check for the error message

2021-03-04 09:39 UTC, renuka-fernando commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
> +                throw new APIMigrationException("Failed to add data to AM_API_RESOURCE_SCOPE_MAPPING table : ", ex);
fixed with https://github.com/wso2-extensions/apim-migration-resources/pull/85/commits/72452355b510866a43d5c954191389ad38475a2b

2021-03-04 09:39 UTC, renuka-fernando commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
> +            throw new APIMigrationException("Failed to add data to AM_API_RESOURCE_SCOPE_MAPPING table : ", e);
fixed with https://github.com/wso2-extensions/apim-migration-resources/pull/85/commits/72452355b510866a43d5c954191389ad38475a2b

2021-03-04 09:40 UTC, renuka-fernando commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
> +            throw new APIMigrationException("Failed to add data to AM_API_RESOURCE_SCOPE_MAPPING table : ", ex);
fixed with https://github.com/wso2-extensions/apim-migration-resources/pull/85/commits/72452355b510866a43d5c954191389ad38475a2b

2021-03-05 03:14 UTC, pubudu538 commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dto/GatewayEnvironmentDTO.java
> +package org.wso2.carbon.apimgt.migration.dto;
Let's add missing license headers.

2021-03-05 03:40 UTC, renuka-fernando commented on migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dto/GatewayEnvironmentDTO.java
> +package org.wso2.carbon.apimgt.migration.dto;
fixed with https://github.com/wso2-extensions/apim-migration-resources/pull/85/commits/a907847e46a736efceaeac98407c2c9e904e4784

2021-03-05 04:52 UTC, pubudu538 approved these changes

2021-03-05 06:28 UTC, isharac approved these changes

2021-03-05 06:51 UTC, merged